//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.allpoint.activities.tablet;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.ListView;
import android.widget.TextView;
import com.allpoint.R.layout;
import com.allpoint.util.IconManager_;
import com.google.android.gms.maps.SupportMapFragment;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class PointDetailsActivity_
    extends PointDetailsActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.point_details);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        shareInflater = ((LayoutInflater) this.getSystemService(Context.LAYOUT_INFLATER_SERVICE));
        hoursInflater = ((LayoutInflater) this.getSystemService(Context.LAYOUT_INFLATER_SERVICE));
        iconManager = IconManager_.getInstance_(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static PointDetailsActivity_.IntentBuilder_ intent(Context context) {
        return new PointDetailsActivity_.IntentBuilder_(context);
    }

    public static PointDetailsActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new PointDetailsActivity_.IntentBuilder_(fragment);
    }

    public static PointDetailsActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new PointDetailsActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        logoView = ((ImageView) hasViews.findViewById(com.allpoint.R.id.iViewRetailerLogo));
        tvPointDistance = ((TextView) hasViews.findViewById(com.allpoint.R.id.tvDetailsPointDistance));
        bottomSearchButton = ((ImageButton) hasViews.findViewById(com.allpoint.R.id.iBtnBottomSearch));
        detailViewServicesTitle = ((TextView) hasViews.findViewById(com.allpoint.R.id.tvServicesTitle));
        btnShare = ((ImageButton) hasViews.findViewById(com.allpoint.R.id.shareButton));
        tvPointName = ((TextView) hasViews.findViewById(com.allpoint.R.id.tvDetailsPointName));
        tvPointAddress = ((TextView) hasViews.findViewById(com.allpoint.R.id.tvDetailsPointAddress));
        tvSearch = ((TextView) hasViews.findViewById(com.allpoint.R.id.iTxtBottomSearch));
        lvServices = ((ListView) hasViews.findViewById(com.allpoint.R.id.listViewServices));
        btnGetHours = ((ImageButton) hasViews.findViewById(com.allpoint.R.id.hoursButton));
        detailViewTitle = ((TextView) hasViews.findViewById(com.allpoint.R.id.tvDetailViewTitle));
        btnCall = ((ImageButton) hasViews.findViewById(com.allpoint.R.id.callButton));
        map = ((ViewGroup) hasViews.findViewById(com.allpoint.R.id.mapDetails));
        mapFragment = ((SupportMapFragment) findSupportFragmentById(com.allpoint.R.id.mapDetails));
        {
            View view = hasViews.findViewById(com.allpoint.R.id.directionButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PointDetailsActivity_.this.onDirectionButtonClicked();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.allpoint.R.id.tvDetailViewTitle);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PointDetailsActivity_.this.onTvDetailViewTitleClick();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.allpoint.R.id.shareButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PointDetailsActivity_.this.onShareButtonClicked();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.allpoint.R.id.iBtnDetailsBack);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PointDetailsActivity_.this.onIbtnDetailsBackClicked();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.allpoint.R.id.callButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PointDetailsActivity_.this.onCallButtonClicked();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.allpoint.R.id.hoursButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PointDetailsActivity_.this.onHoursButtonClicked();
                    }

                }
                );
            }
        }
        afterViews();
    }

    private android.support.v4.app.Fragment findSupportFragmentById(int id) {
        return getSupportFragmentManager().findFragmentById(id);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, PointDetailsActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, PointDetailsActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, PointDetailsActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public PointDetailsActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
