//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.allpoint.util;

import android.content.Context;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class IconManager_
    extends IconManager
{

    private Context context_;
    private static IconManager_ instance_;

    private IconManager_(Context context) {
        context_ = context;
    }

    public static IconManager_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new IconManager_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
    }

}
