//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.allpoint.util;

import android.content.Context;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class Settings_
    extends Settings
{

    private Context context_;
    private static Settings_ instance_;

    private Settings_(Context context) {
        context_ = context;
    }

    public static Settings_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new Settings_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
    }

}
