//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.allpoint.util;

import android.content.Context;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class Utils_
    extends Utils
{

    private Context context_;
    private static Utils_ instance_;

    private Utils_(Context context) {
        context_ = context;
    }

    public static Utils_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new Utils_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
    }

}
