//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.allpoint.services;

import android.content.Context;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class FilterManager_
    extends FilterManager
{

    private Context context_;
    private static FilterManager_ instance_;

    private FilterManager_(Context context) {
        context_ = context;
    }

    public static FilterManager_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new FilterManager_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
    }

}
