//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.allpoint.activities.phone;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.CompoundButton;
import android.widget.CompoundButton.OnCheckedChangeListener;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TextView;
import com.allpoint.R.id;
import com.allpoint.R.layout;
import com.allpoint.services.InternetConnectionManager_;
import com.allpoint.util.Settings_;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class SettingsActivity_
    extends SettingsActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.settings);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        connectionManager = InternetConnectionManager_.getInstance_(this);
        settings = Settings_.getInstance_(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static SettingsActivity_.IntentBuilder_ intent(Context context) {
        return new SettingsActivity_.IntentBuilder_(context);
    }

    public static SettingsActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new SettingsActivity_.IntentBuilder_(fragment);
    }

    public static SettingsActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new SettingsActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        languageSpinner = ((Spinner) hasViews.findViewById(id.language_spinner));
        btnEditprofileIs = ((TextView) hasViews.findViewById(id.btnEditProfile));
        tvSetGeofence = ((TextView) hasViews.findViewById(id.tvSetGeofence));
        settingsTitle = ((TextView) hasViews.findViewById(id.tvSettingsTitle));
        settingsLaunchNearWithMe = ((TextView) hasViews.findViewById(id.tvLaunchNear));
        settingsVisitGooglePlayButton = ((TextView) hasViews.findViewById(id.btnVisitPlay));
        settingsbtnChangePasswordButtonLine = ((TextView) hasViews.findViewById(id.btnChangePasswordLine));
        settingsLanguage = ((TextView) hasViews.findViewById(id.tvLanguage));
        settingsDistanceUnits = ((TextView) hasViews.findViewById(id.tvDistanceUnits));
        settingsFeedbackButton = ((TextView) hasViews.findViewById(id.btnFeedback));
        unitsSpinner = ((Spinner) hasViews.findViewById(id.distance_spinner));
        settingsVersion = ((TextView) hasViews.findViewById(id.tvAppVersion));
        settingsbtnChangePasswordButton = ((TextView) hasViews.findViewById(id.btnChangePassword));
        tvSetting = ((TextView) hasViews.findViewById(id.iTxtBottomMore));
        settingsSearchPreference = ((TextView) hasViews.findViewById(id.tvSearchPreference));
        layGeoFence = ((LinearLayout) hasViews.findViewById(id.layGeoFence));
        launchWithNearMeButton = ((Switch) hasViews.findViewById(id.tBtnLaunchNear));
        launchSettingGeofence = ((Switch) hasViews.findViewById(id.tBtnSetGeofence));
        btnTermsAndCondition = ((TextView) hasViews.findViewById(id.btnTermsAndCond));
        settingsButton = ((ImageButton) hasViews.findViewById(id.iBtnBottomMore));
        {
            View view = hasViews.findViewById(id.btnTermsAndCond);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SettingsActivity_.this.onBtnTermsAndCondClicked();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btnVisitPlay);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SettingsActivity_.this.onBtnVisitPlayClicked();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btnEditProfile);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SettingsActivity_.this.onBtnEditProfileClicked();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btnChangePassword);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SettingsActivity_.this.onBtnChangePswdClick();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btnFeedback);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SettingsActivity_.this.onBtnFeedbackClick();
                    }

                }
                );
            }
        }
        {
            CompoundButton view = ((CompoundButton) hasViews.findViewById(id.tBtnSetGeofence));
            if (view!= null) {
                view.setOnCheckedChangeListener(new OnCheckedChangeListener() {


                    @Override
                    public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                        SettingsActivity_.this.checkedChangedOnSetGeofence(buttonView, isChecked);
                    }

                }
                );
            }
        }
        {
            CompoundButton view = ((CompoundButton) hasViews.findViewById(id.tBtnLaunchNear));
            if (view!= null) {
                view.setOnCheckedChangeListener(new OnCheckedChangeListener() {


                    @Override
                    public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                        SettingsActivity_.this.checkedChangedOnTbtnLaunchNear(buttonView, isChecked);
                    }

                }
                );
            }
        }
        afterViews();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, SettingsActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, SettingsActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, SettingsActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public SettingsActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
